name: localization_lite
description: "A lightweight and easy-to-use package for multilingual support using JSON files. Simplifies adding localization in Flutter apps with minimal setup and integration"
version: 1.0.5
homepage: https://github.com/hesham04Dev/localization_lite

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
